antvis/L7Plot

.github/workflows/release.yml, .github/workflows/test.yml, package.json, packages/l7plot/package.json
=> reduce test time

README.en-US.md, README.md, package.json, packages/l7plot/README.md, website/package.json
=> chore: resolutions monaco editor version

website/package.json
=> chore: upgrade website

packages/l7plot/src/core/map/index.ts, packages/l7plot/src/core/plot/index.ts, packages/l7plot/src/plots/choropleth/index.ts
=> feat: export update event

packages/l7plot/__tests__/unit/adaptor/layer/index.spec.ts, packages/l7plot/__tests__/unit/core/layer/layer-group.test.ts, packages/l7plot/__tests__/unit/core/layer/plot-layer.test.ts, packages/l7plot/src/plots/choropleth/index.ts
=> test: adaptor layer

packages/l7plot/package.json, packages/l7plot/src/index.ts, storybook/package.json, website/package.json
=> chore: publish 0.0.3-alpha.6

.github/workflows/test.yml, packages/l7plot/package.json, packages/l7plot/src/index.ts
=> fix: remove module export for temporary

packages/l7plot/src/plots/flow/constants.ts, packages/l7plot/src/plots/flow/index.ts, packages/l7plot/src/plots/flow/types.ts, website/docs/common/attribute/radiation.zh.md
=> feat: flow radiation style

packages/l7plot/package.json, packages/l7plot/src/index.ts, packages/l7plot/src/layers/dot-layer/helper.ts
=> fix: legend tick

packages/l7plot/src/plots/choropleth/layer.ts, packages/l7plot/src/plots/choropleth/types.ts, storybook/stories/plots/choropleth/ChinaProvince.tsx
=> feat: export china boundary style

packages/l7plot/__tests__/unit/layers/arc-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/area-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/column-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/grid-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/hexbin-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/path-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/prism-layer/index.test.ts, packages/l7plot/__tests__/unit/layers/text-layer/index.test.ts, packages/l7plot/src/plots/choropleth/index.ts
=> fix: update render for choropleth

packages/l7plot/package.json, packages/l7plot/src/index.ts
=> chore: version

packages/l7plot/package.json, packages/l7plot/src/core/layer/plot-layer.ts, packages/l7plot/src/index.ts
=> fix: plot layer change data

packages/l7plot/__tests__/unit/layers/icon-layer/index.test.ts, packages/l7plot/src/index.ts, packages/l7plot/src/layers/icon-layer/index.ts, packages/l7plot/src/layers/icon-layer/types.ts, packages/l7plot/src/plot/types.ts, packages/l7plot/src/types/layer.ts, website/docs/api/layers/icon-layer.en.md, website/docs/api/layers/icon-layer.zh.md, website/docs/api/layers/prism-layer.zh.md, website/docs/common/attribute/color.zh.md, website/docs/common/layers/arc-layer/size.zh.md, website/docs/common/layers/dot-layer/shape.zh.md, website/docs/common/layers/dot-layer/size.zh.md, website/docs/common/layers/path-layer/size.zh.md
```js
import { IconLayer, registerImages } from '@antv/l7plot';
const images = [
{ id: '01', image: 'https://gw.alipayobjects.com/zos/basement_prod/604b5e7f-309e-40db-b95b-4fac746c5153.svg' },
{ id: '02', image: 'https://gw.alipayobjects.com/zos/basement_prod/30580bc9-506f-4438-8c1a-744e082054ec.svg' },
];
registerImages(images);
const iconLayer = new IconLayer({
source: {
data: [{x:120, y: 32.5, id: '02'}],
},
shape: { field: 'id', value: ({ id }) => id },
})
iconLayer.addTo(scene)
```
=> feat: icon layer

package.json, packages/l7plot/package.json, packages/l7plot/src/component/tooltip.ts, packages/l7plot/src/core/layer/layer-group.ts, packages/l7plot/src/core/layer/plot-layer.ts, packages/l7plot/src/core/map/index.ts, packages/l7plot/src/core/plot/index.ts, packages/l7plot/src/index.ts, packages/l7plot/src/plot/index.ts, packages/l7plot/src/plot/types.ts, packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/types/common.ts, packages/l7plot/src/types/layer.ts, packages/l7plot/src/types/map.ts, storybook/package.json, storybook/stories/plugin-scene/ChoroplethDrill.tsx, storybook/stories/plugin-scene/PlotIconLayer.tsx, storybook/stories/plugin-scene/index.stories.tsx, website/docs/api/advanced-plot/index.zh.md, website/docs/api/layers/icon-layer.zh.md, website/docs/api/plot-api/index.zh.md, website/docs/common/attribute/map.zh.md, website/docs/common/layers/dot-layer/shape.zh.md, website/package.json
- add methed `setMapStatus `、`setBgColor `、`addToScene `、`removeFromScene ` for plot
- add methed `getPlotByName `、`removePlotByName `、`removePlotByName `、`addPlot ` for advanced plot
- feat: advanced plot support flow
- fix: repeat register resources
- perf: reduce rendering times for choropleth
=> perf: reduce rendering times

packages/l7plot/package.json, packages/l7plot/src/core/plot/index.ts, packages/l7plot/src/index.ts, packages/l7plot/src/layers/area-layer/adaptor.ts, packages/l7plot/src/layers/area-layer/types.ts, packages/l7plot/src/plots/area/index.ts, packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/plots/choropleth/layer.ts, packages/l7plot/src/plots/choropleth/types.ts, packages/l7plot/src/plots/dot/index.ts, packages/l7plot/src/plots/flow/index.ts, packages/l7plot/src/plots/grid/index.ts, packages/l7plot/src/plots/heatmap/index.ts, packages/l7plot/src/plots/hexbin/index.ts, storybook/package.json, storybook/stories/plots/choropleth/WorldSufei.tsx, website/docs/common/layers/arc-layer/style.zh.md, website/docs/common/layers/area-layer/style.zh.md, website/docs/common/layers/path-layer/style.zh.md, website/package.json
=> fix: chinaBorder update of choropleth

packages/l7plot/package.json, packages/l7plot/src/index.ts, storybook/package.json, website/package.json
=> chore: publish

website/docs/api/components/tooltip.zh.md, website/docs/api/plots/choropleth.zh.md, website/examples/choropleth/administrative/demo/administrative-switch.tsx
=> docs: china border

lerna.json, package.json, packages/component/__tests__/unit/tooltip/index.test.ts, packages/component/package.json, packages/component/src/index.ts, packages/component/src/tooltip/constants.ts, packages/l7plot/package.json, packages/l7plot/src/index.ts, website/docs/api/components/legend.zh.md, website/docs/api/components/tooltip.zh.md
=> docs: domstyle for component

website/api-extractor.json, website/gatsby-config.js, website/package.json
=> chore: website analytics key

storybook/package.json, website/docs/api/plots/choropleth.zh.md, website/package.json
=> docs: choropleth drillup

website/docs/api/plots/choropleth.zh.md
=> docs: joinBy

storybook/stories/plots/area/WorldSufei.tsx, storybook/stories/plots/area/WorldSufeiMove.tsx, storybook/stories/plots/area/index.stories.tsx, storybook/stories/plots/choropleth/WorldSufei.tsx, storybook/stories/plugin-scene/ChoroplethDrill.tsx
=> docs: demo of sufei

package.json, packages/component/package.json, packages/component/src/index.ts, packages/l7plot/package.json, packages/l7plot/src/index.ts, storybook/package.json, website/package.json
=> chore: move l7 to peerDependencies

packages/component/src/legend/category/index.ts, packages/component/src/types/legend.ts, packages/l7plot/package.json, packages/l7plot/src/component/legend.ts, packages/l7plot/src/layers/dot-layer/helper.ts, packages/l7plot/src/plots/heatmap/index.ts, packages/l7plot/src/types/common.ts, packages/l7plot/src/types/legend.ts, storybook/package.json
=> chore: legend type

packages/component/src/legend/category/index.ts
=> chore: text add space

packages/l7plot/src/layers/dot-layer/helper.ts, storybook/stories/component/tooltip/WorldMap.tsx, storybook/stories/component/tooltip/index.stories.tsx, website/docs/api/plot-api/index.zh.md
=> fix: precision number of legend

packages/component/src/index.ts, packages/l7plot/__tests__/unit/plot/index.test.ts, packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/plots/flow/index.ts
=> fix: drill update

packages/component/src/index.ts, packages/l7plot/__tests__/unit/plot/index.test.ts, packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/plots/flow/index.ts, website/docs/api/plots/choropleth.zh.md
=> feat: getCurrentDrillSteps

packages/l7plot/src/plots/choropleth/index.ts
=> fix: 区域地图支持更新中国边界线样式

.github/release.yaml, .github/workflows/release-label.yml
=> ci: conventional release labels

packages/l7plot/src/plots/choropleth/constants.ts, storybook/stories/advanced-plot/ChinaBubbleMap.tsx, storybook/stories/advanced-plot/WorldBubbleMap.tsx, storybook/stories/component/tooltip/WorldMap.tsx, website/docs/api/plots/choropleth.zh.md, website/examples/advanced-plot/muti-plots/demo/china-bubble.ts, website/examples/advanced-plot/muti-plots/demo/world-bubble.ts, website/examples/choropleth/administrative/demo/administrative-switch.tsx, website/examples/choropleth/administrative/demo/china-city.ts, website/examples/choropleth/administrative/demo/hangzhou-city.ts, website/examples/choropleth/administrative/demo/zhejiang-province-district.ts, website/examples/choropleth/administrative/demo/zhejiang-province.ts, website/examples/choropleth/drill/demo/drill-callback.ts, website/examples/choropleth/drill/demo/drill-intercept.ts, website/examples/choropleth/drill/demo/order-drill.ts, website/examples/choropleth/drill/demo/unorder-drill.ts
=> perf: choropleth geo data size

website/docs/api/components/legend.zh.md
=> docs: fix type

website/docs/api/components/tooltip.zh.md
=> docs: fix tooltip type

packages/component/package.json, packages/component/src/index.ts, packages/l7plot/package.json, packages/l7plot/src/index.ts, storybook/package.json, website/package.json
=> chore: v0.0.8

website/docs/manual/faq/index.en.md, website/docs/manual/faq/index.zh.md
=> docs: 新增常见问题 FAQ 文档

packages/l7plot/src/core/plot/index.ts, packages/l7plot/src/plots/choropleth/index.ts, storybook/stories/plots/choropleth/Drill.tsx, website/docs/api/plots/choropleth.zh.md
=> fix: 修复数据更新图例未更新问题

packages/component/package.json, packages/component/src/index.ts, packages/l7plot/package.json, packages/l7plot/src/index.ts, storybook/package.json, website/package.json
=> chore: v0.0.9

packages/l7plot/package.json, packages/l7plot/src/index.ts, storybook/package.json, website/package.json
=> fix: 将 @antv/l7 添加为同等依赖项

README.en-US.md, README.md, packages/l7plot/README.md, website/docs/manual/introduction/index.zh.md, website/examples/advanced-plot/muti-plots/demo/meta.json, website/examples/advanced-plot/muti-plots/demo/world-bubble.ts, website/examples/choropleth/administrative/demo/meta.json, website/examples/choropleth/administrative/demo/world-map.ts, website/examples/choropleth/administrative/demo/zhejiang-province.ts
=> docs: 给网站添加示例截图

README.en-US.md, README.md, packages/l7plot/README.md
=> docs: 更新示例图片地址

lerna.json
=> chore: 修改工程版本变更规则

website/examples/choropleth/administrative/demo/world-map.ts
=> docs: demo for world map

packages/l7plot/src/core/plot/index.ts, packages/l7plot/src/plot/index.ts, packages/l7plot/src/plots/choropleth/index.ts, website/docs/manual/faq/index.zh.md
=> refactor: 修改图层添加顺序为场景加载完成之后

lerna.json, package.json, packages/component/package.json, packages/component/tsconfig.json, packages/composite-layers/tsconfig.json, packages/l7plot/package.json, packages/l7plot/tsconfig.json, storybook/package.json, tsconfig.json, website/package.json
=> chore: 修改工程版本更新逻辑

packages/l7plot/src/plots/choropleth/constants.ts, packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/plots/choropleth/layer.ts, website/docs/api/plots/choropleth.zh.md
=> fix: 行政区域图修复中国港澳线样式

website/gatsby-config.js, website/package.json
=> docs: 集成 DocSearch

packages/composite-layers/README.md, packages/composite-layers/package.json, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/bubble-layer/types.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/types.ts, packages/composite-layers/src/core-layers/heatmap-layer/index.ts, packages/composite-layers/src/core-layers/heatmap-layer/types.ts, packages/composite-layers/src/core-layers/line-layer/index.ts, packages/composite-layers/src/core-layers/point-layer/index.ts, packages/composite-layers/src/core-layers/polygon-layer/index.ts, packages/composite-layers/src/core-layers/text-layer/index.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/index.ts, packages/composite-layers/src/types/attr.ts, packages/composite-layers/src/version.ts
=> chore: 导出类型文件

packages/composite-layers/package.json, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/version.ts, storybook/stories/composite-layers/choropleth-layer/ChinaCitys.tsx
=> fix: 修复复合图层重复更新问题

lerna.json
=> chore: remove version tag

website/docs/api/composite-layers/bubble-layer.zh.md, website/docs/api/composite-layers/choropleth-layer.zh.md, website/docs/common/composite-layers/text-layer/style.zh.md
=> docs: 修改标注类型问题

packages/composite-layers/src/composite-layers/bubble-layer/constants.ts, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/constants.ts, packages/composite-layers/src/composite-layers/icon-layer/constants.ts, packages/composite-layers/src/composite-layers/icon-layer/icon-font.ts, packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/composite-layers/icon-layer/types.ts, packages/composite-layers/src/core-layers/point-layer/index.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/constants.ts, packages/composite-layers/src/index.ts, packages/composite-layers/src/types/category.ts
=> chore: 规范 layer

packages/component/.npmignore, packages/composite-layers/.npmignore, packages/l7plot/.npmignore, packages/l7plot/package.json
=> build: 支持 esm

packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/plots/choropleth/types.ts
=> feat: 地理数据支持自定义请求

packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/plots/choropleth/types.ts, website/docs/api/plots/choropleth.zh.md
=> docs: 文档新增自定义获取数据 API

packages/composite-layers/package.json, packages/l7plot/package.json
- [修改开发环境依赖缺失问题](https://github.com/antvis/L7Plot/commit/4ae45f8a1243e8508d184df2e31749865b856210)
=> chore: 修改开发环境依赖缺失问题

packages/composite-layers/src/composite-layers/icon-layer/icon-font.ts, packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/constants.ts, packages/composite-layers/src/core/core-layer.ts, storybook/stories/composite-layers/polygon-layer/XiHu.tsx
=> feat: 图层更新方法支持更新数据

packages/composite-layers/src/composite-layers/bubble-layer/types.ts, packages/composite-layers/src/composite-layers/choropleth-layer/types.ts, packages/composite-layers/src/composite-layers/icon-layer/types.ts, packages/composite-layers/src/core/composite-layer.ts, website/docs/api/composite-layers/bubble-layer.zh.md, website/docs/api/composite-layers/choropleth-layer.zh.md, website/docs/common/attribute/color.zh.md, website/docs/common/attribute/size.zh.md, website/docs/common/composite-layers/heatmap-layer/size.zh.md, website/docs/common/composite-layers/point-layer/shape.zh.md, website/site/pages/index.less
- [docs: 更新文档 API 样式](https://github.com/antvis/L7Plot/commit/2e3aa27c057cfc76314431b81e1b22ef0e2b52ff)
- [docs: 更新类型注解](https://github.com/antvis/L7Plot/commit/08a5b08ac16d7206ebe7515ad904a99bb9082505)
- [docs: 更新图层属性类型](https://github.com/antvis/L7Plot/commit/b3fa48ad3433503a1294d75651439326c26ef451)
=> docs: 更新文档 API 样式

packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/types/interface.ts
=> chore: 修复图层类型错误问题

packages/component/package.json, packages/composite-layers/package.json, packages/composite-layers/src/core-layers/image-layer/types.ts, packages/composite-layers/src/core-layers/raster-layer/types.ts, packages/composite-layers/src/index.ts, packages/l7plot/package.json, website/docs/api/composite-layers/bubble-layer.zh.md, website/docs/api/composite-layers/choropleth-layer.zh.md, website/docs/common/composite-layers/heatmap-layer/style.zh.md
=> docs: 修复文档 API 归类问题

package.json
=> chore: 升级依赖

scripts/sync-version.js
=> chore: 更新版本工具

packages/composite-layers/src/core-layers/raster-layer/types.ts, website/docs/api/composite-layers/bubble-layer.en.md, website/docs/api/composite-layers/bubble-layer.zh.md, website/docs/api/composite-layers/choropleth-layer.en.md, website/docs/api/composite-layers/choropleth-layer.zh.md, website/docs/api/composite-layers/heatmap-layer.en.md, website/docs/api/composite-layers/heatmap-layer.zh.md, website/docs/api/composite-layers/image-layer.en.md, website/docs/api/composite-layers/image-layer.zh.md, website/docs/api/composite-layers/polygon-layer.en.md, website/docs/api/composite-layers/polygon-layer.zh.md, website/docs/api/composite-layers/raster-layer.en.md, website/docs/api/composite-layers/raster-layer.zh.md, website/docs/api/composite-layers/text-layer.en.md, website/docs/api/composite-layers/text-layer.zh.md, website/docs/common/composite-layers/raster-layer/source.zh.md, website/docs/common/composite-layers/raster-layer/style.zh.md
=> docs: 更新栅格图层文档

packages/composite-layers/src/core/constants.ts
=> fix: 修复图层图例事件

packages/composite-layers/src/composite-layers/icon-layer/types.ts, website/docs/api/composite-layers/icon-font-layer.en.md, website/docs/api/composite-layers/icon-font-layer.zh.md, website/docs/api/composite-layers/icon-image-layer.en.md, website/docs/api/composite-layers/icon-image-layer.zh.md
=> docs: 图标图层文档完善

packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/core-layer.ts, packages/composite-layers/src/types/interface.ts
=> chore: 给复合图层显隐方法类型补充

packages/composite-layers/src/core/layer-group.ts
=> fix: 修复复合图层从场景中移除 bug

packages/composite-layers/src/types/interface.ts, packages/l7plot/__tests__/unit/core/plot/index.test.ts, packages/l7plot/src/component/legend.ts, packages/l7plot/src/core/map/index.ts, packages/l7plot/src/types/control.ts
=> fix: 图层接口类型缺失

packages/composite-layers/src/core/core-layer.ts
=> fix: 修复 maxZoom 更新失败问题

packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/core-layer.ts, packages/composite-layers/src/types/interface.ts, website/docs/common/composite-layers/composite-common/method.zh.md, website/docs/common/composite-layers/core-common/method.zh.md
=> feat: 核心图层新增 getSource 方法

packages/l7plot/__tests__/unit/plots/dot/index.test.ts, packages/l7plot/__tests__/unit/plots/heatmap/index.test.ts, packages/l7plot/src/core/map/index.ts
=> fix: 获取图层图例数据异步情况

package.json, packages/composite-layers/package.json, packages/composite-layers/src/composite-layers/bubble-layer/constants.ts, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/bubble-layer/types.ts, packages/composite-layers/src/composite-layers/choropleth-layer/constants.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/types.ts, packages/composite-layers/src/composite-layers/common/multi-select.ts, packages/composite-layers/src/composite-layers/icon-layer/constants.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/composite-layers/icon-layer/types.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/layer-group.ts, packages/composite-layers/src/types/interface.ts, packages/composite-layers/src/utils/index.ts, packages/composite-layers/src/utils/keypress.ts, storybook/stories/composite-layers/choropleth-layer/Select.tsx, storybook/stories/composite-layers/choropleth-layer/index.stories.tsx, website/docs/api/composite-layers/bubble-layer.zh.md, website/docs/api/composite-layers/choropleth-layer.zh.md, website/docs/api/composite-layers/icon-font-layer.zh.md, website/docs/api/composite-layers/icon-image-layer.zh.md, website/docs/common/base-layers/base-common/method.zh.md, website/docs/common/composite-layers/composite-common/method.zh.md
=> feat: 复合图层多选功能

packages/composite-layers/src/composite-layers/common/multi-select.ts
=> fix: 修复复合图层多选触发条件

package.json, packages/composite-layers/package.json, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/types.ts, packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts, packages/composite-layers/src/composite-layers/icon-layer/types.ts, packages/l7plot/package.json, packages/l7plot/src/layers/area-layer/adaptor.ts, packages/l7plot/src/layers/area-layer/types.ts, storybook/package.json, storybook/stories/core-layers/index.stories.tsx, storybook/stories/core-layers/rastertileLayer.tsx, storybook/stories/plots/choropleth/WorldSufei.tsx, website/docs/common/layers/area-layer/style.zh.md, website/offline-examples/choropleth/administrative/demo/world-map.ts, website/package.json
- [ ✅] fixed geotiff 依赖
- [ ✅] iconimage 加载状态
- [ ✅]  移除fillbottom color
- - [ ✅]  L7 version
=> fix: icon layer image 加载时机

storybook/stories/core-layers/PointLayer.tsx, storybook/stories/core-layers/index.stories.tsx
=> docs: 给点图层添加示例

README.en-US.md, README.md, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/core-layer.ts, packages/composite-layers/src/types/interface.ts, packages/l7plot/README.md, storybook/stories/composite-layers/bubble-layer/Earthquake.tsx, storybook/stories/core-layers/TextLayer.tsx, storybook/stories/core-layers/index.stories.tsx, website/docs/api/plot-api/index.zh.md, website/docs/common/base-layers/text-layer/style.zh.md, website/gatsby-config.js
=> fix: 修复复合图层批量更新问题

scripts/sync-version.js
=> chore: 修改同步版本脚步

packages/composite-layers/package.json, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/constants.ts, packages/composite-layers/src/core/core-layer.ts, packages/composite-layers/src/core/layer-group.ts, packages/l7plot/package.json, packages/l7plot/src/core/map/index.ts, packages/l7plot/src/plots/choropleth/index.ts, packages/l7plot/src/types/map.ts, storybook/package.json, storybook/stories/composite-layers/bubble-layer/Earthquake.tsx, website/docs/common/attribute/map.zh.md
=> fix: 修复图层事件&修复复合图层 Size 映射问题

packages/composite-layers/src/core/composite-layer.ts, storybook/stories/composite-layers/bubble-layer/Earthquake.tsx
=> fix: 修复图层切换显隐方法

README.en-US.md, README.md, packages/l7plot/README.md, website/docs/manual/quick-start/index.zh.md
=> docs: 更新安装引导文档

website/docs/common/base-layers/text-layer/style.zh.md, website/gatsby-config.js
=> chore: 恢复源站点地址

packages/l7plot/src/plots/choropleth/index.ts
=> fix: 修复行政区域图标签更新问题

packages/composite-layers/src/composite-layers/icon-layer/icon-font.ts, packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, packages/composite-layers/src/core/core-layer.ts
=> fix: 修复图标复合图层初始化事件

packages/l7plot/src/core/map/index.ts, website/docs/api/plot-api/index.zh.md
=> fix: setMapStatus参数类型改成可选

packages/composite-layers/src/composite-layers/icon-layer/constants.ts
=> fix: iconLayer 加 blend: normal 默认值

packages/composite-layers/src/core-layers/text-layer/index.ts, storybook/stories/composite-layers/choropleth-layer/Active.tsx, storybook/stories/composite-layers/choropleth-layer/index.stories.tsx
=> fix: 修复文本图层更新问题

packages/l7plot/src/types/layer.ts, website/docs/common/base-layers/point-layer/style.zh.md, website/docs/common/layers/dot-layer/style.zh.md
=> fix: support unit option in dot style config

packages/l7plot/src/plots/choropleth/index.ts
=> fix: emit 'drillup' event in `drillUp` function

packages/l7plot/src/plots/choropleth/index.ts
=> fix: emit 'drilldown' event in `drillDown` function

packages/composite-layers/__tests__/unit/composite-layers/flow-layer/index.test.ts, packages/composite-layers/src/composite-layers/flow-layer/constants.ts, packages/composite-layers/src/composite-layers/flow-layer/data/build-index.ts, packages/composite-layers/src/composite-layers/flow-layer/index.ts, packages/composite-layers/src/composite-layers/flow-layer/types/index.ts, packages/composite-layers/src/composite-layers/flow-layer/utils/style.ts, packages/composite-layers/src/core-layers/line-layer/types.ts, packages/composite-layers/src/core-layers/point-layer/types.ts, packages/composite-layers/src/types/attr.ts, website/docs/api/composite-layers/flow-layer.zh.md, website/docs/common/base-layers/line-layer/shape.zh.md, website/examples/composite/trafficFlow/demo/base.js
- Layer style 中样式值映射类型更新
- FlowLayer 适配 L7 LineLayer shape 升级为 'flowline'
- FlowLayer 参数新增客流线的边框样式
=> feat: 完善 FlowLayer 箭头、线间隔等新特性

packages/l7plot/src/plots/choropleth/layer.ts
=> fix: 解决不支持透明度映射问题

packages/composite-layers/__tests__/unit/composite-layers/flow-layer/index.test.ts, packages/composite-layers/src/composite-layers/flow-layer/constants.ts, packages/composite-layers/src/composite-layers/flow-layer/data/transform.ts, packages/composite-layers/src/composite-layers/flow-layer/index.ts, packages/composite-layers/src/composite-layers/flow-layer/types/index.ts, packages/composite-layers/src/composite-layers/flow-layer/utils/style.ts, website/docs/api/composite-layers/flow-layer.zh.md, website/docs/common/composite-layers/composite-common/method.zh.md
=> feat：FlowLayer 新增客流点名称和交互逻辑

.github/workflows/lint.yml, .github/workflows/test.yml, packages/composite-layers/src/version.ts, packages/l7plot/__tests__/helper/plot.ts, packages/l7plot/__tests__/unit/plots/heatmap/index.test.ts, packages/l7plot/src/core/map/constants.ts
=> fix: 修复图层双击事件丢失问题

package.json, packages/composite-layers/src/composite-layers/bubble-layer/types.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/types.ts, packages/composite-layers/src/composite-layers/common/label-layer.ts, packages/composite-layers/src/composite-layers/icon-layer/types.ts, packages/composite-layers/src/core/composite-layer.ts, packages/composite-layers/src/core/core-layer.ts, scripts/clean-deps.sh
=> feat: layer 支持数据过滤属性

packages/composite-layers/package.json, packages/composite-layers/src/composite-layers/flow-layer/data/transform.ts, packages/composite-layers/src/composite-layers/flow-layer/index.ts, packages/composite-layers/src/composite-layers/flow-layer/types/index.ts
=> feat:  升级 FlowLayer 部分特性

website/.dumirc.ts, website/package.json
=> chore: 官网高德底图 token 设置

packages/composite-layers/src/core-layers/heatmap-layer/types.ts, packages/composite-layers/src/core-layers/raster-layer/types.ts, packages/composite-layers/src/types/common.ts
=> fix: 同步类型修改

lerna.json, package.json
=> chore: 升级 lerna

packages/l7plot/package.json, storybook/stories/composite-layers/icon-layer/iconImageScale.tsx, storybook/stories/composite-layers/icon-layer/index.stories.tsx
=> chore: 图标图层案例

packages/composite-layers/src/utils/index.ts, storybook/stories/composite-layers/bubble-layer/ScaleUpdate.tsx, storybook/stories/composite-layers/bubble-layer/index.stories.tsx
https://riddle.alibaba-inc.com/riddles/32823b5c
https://riddle.alibaba-inc.com/riddles/1dcb1eb5
=> fix: 修复图层 scale 更新问题

packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts, storybook/stories/composite-layers/icon-layer/iconImageAtlas.tsx, storybook/stories/composite-layers/icon-layer/index.stories.tsx
https://github.com/antvis/L7VP/issues/90
=> fix: 修复 IconImageLayer 支持更新图片资源

packages/l7plot/src/layers/dot-layer/helper.ts
=> fix: legend round value

packages/l7plot/package.json, packages/l7plot/src/core/map/constants.ts, packages/l7plot/src/core/plot/index.ts, packages/l7plot/src/layers/area-layer/index.ts, packages/l7plot/src/plots/choropleth/index.ts, storybook/package.json
=> fix: 修复 Choropleth 下钻 Legend 更新不同步

.github/workflows/lint.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/test.yml, packages/composite-layers/src/composite-layers/bubble-layer/index.ts, packages/composite-layers/src/composite-layers/choropleth-layer/index.ts, packages/composite-layers/src/composite-layers/icon-layer/icon.ts
=> feat: 复合图层 API 支持单选
